import requests

# URL where Ollama runs locally
OLLAMA_URL = "http://localhost:11434/api/generate"

# Model name installed in Ollama 
MODEL = "llama3"


def analyze_speech(transcript):
    """
    This function sends the transcript to Ollama
    and asks the LLM to evaluate the speech.
    """

    # Prompt given to the LLM
    prompt = f"""
You are a public speaking coach.

Analyze the following speech transcript and give feedback.

Give:
- Grammar mistakes
- Clarity of speech
- Filler words used
- Suggestions to improve
- Score out of 10

Transcript:
{transcript}
"""

    # Data sent to Ollama API
    data = {
        "model": MODEL,
        "prompt": prompt,
        "stream": False   # we want full response at once
    }

    # Sending request to local Ollama server
    response = requests.post(OLLAMA_URL, json=data)

    # Convert response to JSON and extract text generated by model
    result = response.json()
    return result["response"]