import requests

# URL where Ollama runs locally
OLLAMA_URL = "http://localhost:11434/api/generate"

# Model name installed in Ollama 
MODEL = "gemma3:12b"


def analyze_transcript(transcript):

    # Prompt LLM to refine raw transcript
    prompt = f"""
        You are given a raw speech-to-text transcript. The transcript may contain errors such as misheard words, missing punctuation, incorrect grammar, or fragmented sentences.

        Your task is to:
        - Correct transcription errors based on context
        - Some words might be transcribed incorrectly, so replace incorrect or misheard words with the most likely correct words
        - Fix grammar and sentence structure
        - Add proper punctuation
        - Keep the original meaning unchanged

        IMPORTANT RULES:
        - Do NOT add new information
        - Do NOT summarize or shorten
        - Do NOT explain anything
        - Output ONLY the corrected transcript

        Raw transcript:
        {transcript}
    """

    # Data sent to Ollama API
    data = {
        "model": MODEL,
        "prompt": prompt,
        "options": {
            "keep_alive": 0 # unload model from memory after transcription
        },
        "stream": False   # provide full response
    }

    # Sending request to local Ollama server
    response = requests.post(OLLAMA_URL, json=data)

    # Convert response to JSON and extract text generated by model
    result = response.json()
    return result["response"]